### PR TITLE
Added Contributing.md

### PR DESCRIPTION
**Pull request by troy0820**

### CODE REVIEW

**Comment by guillermoandrae** [comment]
I was actually referring to this: https://github.com/blog/1184-contributing-guidelines

We'll already know who is contributing to the project through commit history and graphs.

**Comment by troy0820** [comment]
Oh...................Okay

**Comment by guillermoandrae** [comment]
@troy0820 should I close this?

**Comment by troy0820** [comment]
Yeah you can close this.

**Pull request closed without merging**
